import type { NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to my Commenting App Demo!</h1>
        <div className={styles.grid}>
          <a onClick={() => router.push("/posts")} className={styles.card}>
            <h2>Commenting Demo &rarr; Click Here</h2>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
